version: "3.7"
services:

  # Frontend
  front:
    build:
      context: ./front/
      target: base
    command: npm run serve
    restart: "no"
    environment:
      NODE_ENV: development
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public

  # API
  api:
    command: npm run dev
    restart: "no"
    environment:
      NODE_ENV: development
    volumes:
      - ./server/src:/app/src
      - ./server/migrations:/app/migrations

  # Builder
  builder:
    command: npm run dev
    restart: "no"
    environment:
      NODE_ENV: development
    volumes:
      - ./builder/src:/app/src

  nest-server:
    image: ravenos/nest-server
    networks:
      - backend
    ports:
      - 80:80
    environment:
      RAVEN_NEST_SERVER_AUTH_TOKEN: ${APIKEYS_NEST_SERVER}
